# Parameters for global planner
perimeter: [[-.2, -.235], [.2, -.235], [.2, .235], [-.2, .235]]
goal_tol: [0.5, 0.5, 0.1]
vel: 0.5
time_45_deg: 10
obs_thresh: 100
inscribed_thresh: 99
possibly_circumscribed_thresh: 98