#!/usr/bin/env python

"""
Global Planner for Mushr Navigation.

Author: Doerr, Schiffer
"""

import numpy as np
import rospy
import yaml
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import OccupancyGrid, Path
from pysbpl import planner, map_util


class GlobalPlanner:
    """ROS Wrapper for pysbpl Planner."""

    def __init__(self, name):
        """
        Initialize global planner.

        Attributes:
            name (string) rosnode name

        """
        rospy.init_node(name, anonymous=True)

        self.mprim_path = rospy.get_param("~mprim_path")

        self.start = None
        self.path = None
        self.map = map_util.Map(mprim_path=self.mprim_path) 

        # initialize subscribers
        self.goal_sub = rospy.Subscriber(
            rospy.get_param("~goal_topic"), PoseStamped, self.goal_cb, queue_size=1
        )
        self.start_sub = rospy.Subscriber(
            rospy.get_param("~start_topic"),
            PoseStamped,
            self.set_start_cb,
            queue_size=1,
        )
        self.map_sub = rospy.Subscriber(
            rospy.get_param("~map"), OccupancyGrid, self.set_map_cb, queue_size=1
        )

        # initialize publisher
        self.path_publisher = rospy.Publisher(
            rospy.get_param("~path_topic"), Path, queue_size=1
        )

        config_file = open(rospy.get_param("~config_path"))
        self.params = yaml.load(config_file)

        rate = rospy.Rate(3)
        while not rospy.is_shutdown():
            rate.sleep()
            if self.path is not None:
                self.path_publisher.publish(self.path)

    def goal_cb(self, msg):
        """
        Plan a path from recorded start to new goal.

        Attributes:
            msg (geometry_msgs/PoseStamped): goal position

        """
        self.params["map"] = self.map
        self.params["perimeter"] = [
            [-0.2, -0.235],
            [0.2, -0.235],
            [0.2, 0.235],
            [-0.2, 0.235],
        ]

        self.params["mprim_path"] = self.mprim_path.encode("utf-8")
        goal = [msg.pose.position.x, msg.pose.position.y, msg.pose.position.z]

        print("Planning with pysbpl")
        print("Start: " + str(self.start))
        print("Goal: " + str(goal))

        # TODO will want to do this only once with big maps
        sbpl_planner = planner.Planner(**self.params)

        path, headings, actions = sbpl_planner.plan(self.start, goal, allocated_time=10)

        print("Path created: {}".format(path))

    def set_start_cb(self, msg):
        """
        Record the new car position as the start.

        Attributes:
            msg (geometry_msgs/PoseStamped): goal position

        """
        self.start = [msg.pose.position.x, msg.pose.position.y, msg.pose.position.z]

    def set_map_cb(self, msg):
        """
        Load and save the map.

        Attributes:
            msg (nav_msgs/OccupancyGrid): map representation

        """
        img = np.array(np.reshape(msg.data, (msg.info.height, msg.info.width)), dtype=np.float32)
        img[img == -1] = 1
        origin = [
            msg.info.origin.position.x,
            msg.info.origin.position.y,
            msg.info.origin.position.z,
        ]
        self.map.load_map(img, msg.info.resolution, origin, 0.1, 0.09)

if __name__ == "__main__":
    global_planner = GlobalPlanner("global_planner")
